---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    jetic.io/deployment.uuid: "ad17763c-603e-4471-b991-c3df365441b7"
    jetic.io/integration.name: "int1"
    jetic.io/integration.uuid: "9176a9f9-fa46-4a78-b110-3e1cba25cc6c"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "true"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4439e5db-2de0-4b36-9596-a4b01910204b"
  name: "int1"
spec:
  configuration:
  - type: "property"
    value: "quarkus.log.console.color=true"
  - type: "property"
    value: "quarkus.log.console.level=INFO"
  dependencies:
  - "mvn:io.jetic.analyzer:jetic-analyzer:3.1.4"
  replicas: 1
  resources: []
  sources:
  - compression: false
    content: |+
      //
      // To run this integration use:
      //
      // kamel run int1.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=int1

      import io.jetic.analyzer.JeticAnalyzer

      // activate JETIC.IO Data Analyzer
      JeticAnalyzer.activate(getContext())

    name: "int1.groovy"
  traits:
    jolokia:
      configuration:
        enabled: true
    logging:
      configuration:
        enabled: true
        level: "DEBUG"
    owner:
      configuration:
        enabled: true
        targetLabels:
        - "jetic.io/data.analyzer"
        - "jetic.io/deployment.uuid"
        - "jetic.io/integration.name"
        - "jetic.io/integration.uuid"
        - "jetic.io/log.level"
        - "jetic.io/open.api.host"
        - "jetic.io/profile.name"
        - "jetic.io/profile.uuid"
