---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    jetic.io/deployment.uuid: "d09fc7de-c2eb-403f-a70e-0345093bc4d6"
    jetic.io/integration.name: "int3"
    jetic.io/integration.uuid: "8f698bb4-2c3f-4798-9cd9-29a1884940ff"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "true"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4439e5db-2de0-4b36-9596-a4b01910204b"
  name: "int3"
spec:
  configuration:
  - type: "property"
    value: "quarkus.log.console.color=true"
  - type: "property"
    value: "quarkus.log.console.level=INFO"
  dependencies:
  - "mvn:io.jetic.analyzer:jetic-analyzer:3.1.4"
  replicas: 1
  resources: []
  sources:
  - compression: false
    content: |+
      //
      // To run this integration use:
      //
      // kamel run int3.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=int3

      import io.jetic.analyzer.JeticAnalyzer

      // activate JETIC.IO Data Analyzer
      JeticAnalyzer.activate(getContext())

    name: "int3.groovy"
  traits:
    jolokia:
      configuration:
        enabled: true
    logging:
      configuration:
        enabled: true
        level: "DEBUG"
    owner:
      configuration:
        enabled: true
        targetLabels:
        - "jetic.io/data.analyzer"
        - "jetic.io/deployment.uuid"
        - "jetic.io/integration.name"
        - "jetic.io/integration.uuid"
        - "jetic.io/log.level"
        - "jetic.io/open.api.host"
        - "jetic.io/profile.name"
        - "jetic.io/profile.uuid"
