---
apiVersion: "v1"
data:
  application.properties: "quarkus.log.console.level=INFO"
kind: "ConfigMap"
metadata:
  labels:
    camel.apache.org/integration: "new"
    jetic.io/deployment.uuid: "85fb8536-237d-42f1-9de5-6b6670efaf13"
    jetic.io/integration.name: "new"
    jetic.io/integration.uuid: "85fb8536-237d-42f1-9de5-6b6670efaf13"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "true"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4303a068-e7ae-47ff-b8c0-18ccd067bc16"
  name: "new-properties"
---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    camel.apache.org/integration: "new"
    jetic.io/deployment.uuid: "85fb8536-237d-42f1-9de5-6b6670efaf13"
    jetic.io/integration.name: "new"
    jetic.io/integration.uuid: "85fb8536-237d-42f1-9de5-6b6670efaf13"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "true"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4303a068-e7ae-47ff-b8c0-18ccd067bc16"
  name: "new"
spec:
  dependencies:
  - "mvn:io.jetic.analyzer:jetic-analyzer:2.2.4"
  replicas: 1
  flows: []
  sources:
  - compression: false
    content: |+
      //
      // To run this integration use:
      //
      // kamel run new.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=new

      import io.jetic.analyzer.JeticAnalyzer

      // activate JETIC.IO Data Analyzer
      JeticAnalyzer.activate(getContext())

    name: "new.groovy"
  traits:
    addons: {}
    builder:
      properties:
      - "quarkus.application.name=new"
      - "quarkus.profile=Default"
    jolokia:
      enabled: true
    logging:
      color: true
      level: "INFO"
    mount:
      configs:
      - "configmap:new-properties"
    owner:
      enabled: true
      targetLabels:
      - "jetic.io/data.analyzer"
      - "jetic.io/deployment.uuid"
      - "jetic.io/integration.name"
      - "jetic.io/integration.uuid"
      - "jetic.io/log.level"
      - "jetic.io/open.api.host"
      - "jetic.io/profile.name"
      - "jetic.io/profile.uuid"
