---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    jetic.io/deployment.uuid: "d1682f71-52b7-44f1-8524-44deb6664bea"
    jetic.io/integration.name: "test22"
    jetic.io/integration.uuid: "2f0a4e64-a059-4412-813d-4ebb7ba728b4"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "true"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "827bdf5a-a018-4e6b-b454-65b975d49930"
  name: "test22"
spec:
  configuration:
  - type: "property"
    value: "quarkus.log.console.color=true"
  - type: "property"
    value: "quarkus.log.console.level=INFO"
  dependencies:
  - "mvn:io.jetic.analyzer:jetic-analyzer:3.1.4"
  replicas: 1
  resources: []
  sources:
  - compression: false
    content: |+
      //
      // To run this integration use:
      //
      // kamel run test22.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=test22

      import io.jetic.analyzer.JeticAnalyzer

      // activate JETIC.IO Data Analyzer
      JeticAnalyzer.activate(getContext())

    name: "test22.groovy"
  traits:
    jolokia:
      configuration:
        enabled: true
    logging:
      configuration:
        enabled: true
        level: "DEBUG"
    owner:
      configuration:
        enabled: true
        targetLabels:
        - "jetic.io/data.analyzer"
        - "jetic.io/deployment.uuid"
        - "jetic.io/integration.name"
        - "jetic.io/integration.uuid"
        - "jetic.io/log.level"
        - "jetic.io/open.api.host"
        - "jetic.io/profile.name"
        - "jetic.io/profile.uuid"
