---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    jetic.io/deployment.uuid: "f5da9f0f-6016-439c-9abb-73edbcaa907f"
    jetic.io/integration.name: "test239"
    jetic.io/integration.uuid: "10e124d4-a326-4f49-b8f2-b53bf887014f"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "true"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "827bdf5a-a018-4e6b-b454-65b975d49930"
  name: "test239"
spec:
  configuration:
  - type: "property"
    value: "quarkus.log.console.color=true"
  - type: "property"
    value: "quarkus.log.console.level=INFO"
  dependencies:
  - "mvn:io.jetic.analyzer:jetic-analyzer:2.2.4"
  replicas: 1
  resources: []
  sources:
  - compression: false
    content: |+
      //
      // To run this integration use:
      //
      // kamel run test239.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=test239

      import io.jetic.analyzer.JeticAnalyzer

      // activate JETIC.IO Data Analyzer
      JeticAnalyzer.activate(getContext())

    name: "test239.groovy"
  traits:
    jolokia:
      configuration:
        enabled: true
    logging:
      configuration:
        enabled: true
        level: "DEBUG"
    owner:
      configuration:
        enabled: true
        targetLabels:
        - "jetic.io/data.analyzer"
        - "jetic.io/deployment.uuid"
        - "jetic.io/integration.name"
        - "jetic.io/integration.uuid"
        - "jetic.io/log.level"
        - "jetic.io/open.api.host"
        - "jetic.io/profile.name"
        - "jetic.io/profile.uuid"
