---
apiVersion: "v1"
data:
  application.properties: "quarkus.log.console.level=INFO"
kind: "ConfigMap"
metadata:
  annotations: {}
  labels:
    camel.apache.org/integration: "test2"
    jetic.io/deployment.uuid: "f603d5bd-c96a-48d6-8724-8b1d45281ee0"
    jetic.io/integration.name: "test2"
    jetic.io/integration.revision: "2"
    jetic.io/integration.uuid: "f603d5bd-c96a-48d6-8724-8b1d45281ee0"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "false"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4439e5db-2de0-4b36-9596-a4b01910204b"
  name: "test2-properties"
---
apiVersion: "v1"
data: {}
kind: "ConfigMap"
metadata:
  annotations: {}
  labels:
    camel.apache.org/integration: "test2"
    jetic.io/deployment.uuid: "f603d5bd-c96a-48d6-8724-8b1d45281ee0"
    jetic.io/integration.name: "test2"
    jetic.io/integration.revision: "2"
    jetic.io/integration.uuid: "f603d5bd-c96a-48d6-8724-8b1d45281ee0"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "false"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4439e5db-2de0-4b36-9596-a4b01910204b"
  name: "test2-resources"
---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    camel.apache.org/integration: "test2"
    jetic.io/deployment.uuid: "f603d5bd-c96a-48d6-8724-8b1d45281ee0"
    jetic.io/integration.name: "test2"
    jetic.io/integration.revision: "2"
    jetic.io/integration.uuid: "f603d5bd-c96a-48d6-8724-8b1d45281ee0"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "false"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4439e5db-2de0-4b36-9596-a4b01910204b"
  name: "test2"
spec:
  dependencies: []
  replicas: 1
  sources:
  - compression: false
    content: |+
      //
      // To run this integration use:
      //
      // kamel run test2.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=test2

    name: "test2.groovy"
  traits:
    addons: {}
    builder:
      properties:
      - "quarkus.application.name=test2"
      - "quarkus.profile=Default"
    environment:
      vars:
      - "TEST=2024-04-18T15:34:36.625582518"
    logging:
      color: true
      level: "INFO"
    mount:
      configs:
      - "configmap:test2-properties"
      resources:
      - "configmap:test2-resources"
    owner:
      enabled: true
      targetLabels:
      - "jetic.io/data.analyzer"
      - "jetic.io/deployment.uuid"
      - "jetic.io/integration.name"
      - "jetic.io/integration.revision"
      - "jetic.io/integration.uuid"
      - "jetic.io/log.level"
      - "jetic.io/open.api.host"
      - "jetic.io/profile.name"
      - "jetic.io/profile.uuid"
