---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    jetic.io/deployment.uuid: "f0c12da3-76b9-43f0-9820-b4783cd6902e"
    jetic.io/integration.name: "testgitFetching"
    jetic.io/integration.uuid: "bfa40c45-cbb5-4311-9eff-6748428d6de1"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "true"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4439e5db-2de0-4b36-9596-a4b01910204b"
  name: "testgitfetching"
spec:
  configuration:
  - type: "property"
    value: "quarkus.log.console.color=true"
  - type: "property"
    value: "quarkus.log.console.level=INFO"
  dependencies:
  - "mvn:io.jetic.analyzer:jetic-analyzer:3.1.4"
  replicas: 1
  resources: []
  sources:
  - compression: false
    content: |+
      //
      // To run this integration use:
      //
      // kamel run testgitFetching.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=testgitFetching

      import io.jetic.analyzer.JeticAnalyzer

      // activate JETIC.IO Data Analyzer
      JeticAnalyzer.activate(getContext())

    name: "testgitFetching.groovy"
  traits:
    jolokia:
      configuration:
        enabled: true
    logging:
      configuration:
        enabled: true
        level: "DEBUG"
    owner:
      configuration:
        enabled: true
        targetLabels:
        - "jetic.io/data.analyzer"
        - "jetic.io/deployment.uuid"
        - "jetic.io/integration.name"
        - "jetic.io/integration.uuid"
        - "jetic.io/log.level"
        - "jetic.io/open.api.host"
        - "jetic.io/profile.name"
        - "jetic.io/profile.uuid"
