---
apiVersion: "v1"
data:
  application.properties: "quarkus.log.console.level=INFO"
kind: "ConfigMap"
metadata:
  annotations: {}
  labels:
    camel.apache.org/integration: "test"
    jetic.io/deployment.uuid: "cd30cdba-d039-402d-ac14-389491ec1209"
    jetic.io/integration.name: "test"
    jetic.io/integration.revision: "1"
    jetic.io/integration.uuid: "cd30cdba-d039-402d-ac14-389491ec1209"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "false"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4439e5db-2de0-4b36-9596-a4b01910204b"
  name: "test-properties"
---
apiVersion: "camel.apache.org/v1"
kind: "Integration"
metadata:
  labels:
    camel.apache.org/integration: "test"
    jetic.io/deployment.uuid: "cd30cdba-d039-402d-ac14-389491ec1209"
    jetic.io/integration.name: "test"
    jetic.io/integration.revision: "1"
    jetic.io/integration.uuid: "cd30cdba-d039-402d-ac14-389491ec1209"
    jetic.io/log.level: "INFO"
    jetic.io/data.analyzer: "false"
    jetic.io/profile.name: "Default"
    jetic.io/profile.uuid: "4439e5db-2de0-4b36-9596-a4b01910204b"
  name: "test"
spec:
  dependencies: []
  replicas: 1
  sources:
  - compression: false
    content: |+
      //
      // To run this integration use:
      //
      // kamel run test.groovy
      //

      // camel-k: language=groovy
      // camel-k: name=test

    name: "test.groovy"
  traits:
    addons: {}
    builder:
      properties:
      - "quarkus.application.name=test"
      - "quarkus.profile=Default"
    logging:
      color: true
      level: "INFO"
    mount:
      configs:
      - "configmap:test-properties"
    owner:
      enabled: true
      targetLabels:
      - "jetic.io/data.analyzer"
      - "jetic.io/deployment.uuid"
      - "jetic.io/integration.name"
      - "jetic.io/integration.revision"
      - "jetic.io/integration.uuid"
      - "jetic.io/log.level"
      - "jetic.io/open.api.host"
      - "jetic.io/profile.name"
      - "jetic.io/profile.uuid"
